//
// Created by thatzokay on 05-09-2025.
//

#ifndef PICO_SEGA_LED_LED_H
#define PICO_SEGA_LED_LED_H

#endif //PICO_SEGA_LED_LED_H

enum
{
    LED_CMD_GET_BOARD_INFO = 0xF0,
    LED_CMD_GET_FIRM_SUM = 0xF2,
    LED_CMD_GET_PROTOCOL_VER = 0xF3,
    LED_CMD_TIMEOUT = 0x11,
    LED_CMD_RESET = 0x10,
    LED_CMD_GET_BOARD_STATUS = 0xF1,
    LED_CMD_DISABLE_RESPONSE = 0x14,
    LED_CMD_SET_LED = 0x82,
    LED_CMD_SET_LED_FADE = 0x83,
    LED_CMD_SET_LED_FADE_PATTERN = 0x84,
    LED_CMD_SET_COUNT = 0x86,
    LED_CMD_BOOTLOADER = 0xFD,
};